version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  nats:
    image: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  tzapp:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - nats